dist: trusty
sudo: required
language: c
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq pdftk poppler-utils language-pack-pt
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz 
- tar -xf install-tl-unx.tar.gz && cd install-tl-* && sudo ./install-tl -no-gui -profile ../dependencias-texlive.profile && cd ..
- export PATH=$PATH:/usr/local/texlive/2016/bin/x86_64-linux
script:
- tlmgr --version
- latexmk -v
- xelatex -v
- pdftotext -v
- ./build.sh
